http://localhost:3000/alunos

###

GET http://localhost:3000/alunos/1

###

POST http://localhost:3000/alunos HTTP/1.1
content-type: application/json

{
    "name": "yas",
    "age": 12,
    "contact": "999999999"
}

###

PUT http://localhost:3000/alunos/4 HTTP/1.1
content-type: application/json

{
  "name": "Ana",
  "age": 12,
  "contact": "999999999"
}

###

DELETE http://localhost:3000/alunos/2
